### ISSUE TITLE
Remove / overwrite css

### ISSUE THREAD

**Issue by philoliver** [uiuniversal/ngu-carousel#132]
Hi,

The tiles automatically come with `class="tile"` and a box-shadow. Is there a way via the `config` to remove/overwrite this class?

**Comment by sheikalthaf** [comment]
@philoliver it is not mandatory to use `ngu-tile`. replace with a `div` tag with className `item`

**Comment by somq** [comment]
```scss
:host ::ng-deep .tile {
  box-shadow: none !important;
}

```

Dirty,  but does the job. Meh :shrug:
